---
## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: "off"
gso: "off"
gro: "off"
lro: "off"
highdma: "on"
rx_gro_hw: "off"
rx_gro_list: "off"
tx_gso_robust: "off"
rx_checksumming: "off"
tx_checksumming: "off"
tx_nocache_copy: "off"
receive_hashing: "on"
scatter_gather: "on"
rx_udp_gro_forwarding: "off"
tx_udp_tnl_segmentation: "off"
tx_udp_tnl_csum_segmentation: "off"

## Ethernet flow control
## https://en.wikipedia.org/wiki/Ethernet_flow_control
autoneg: "off"
rx: "off"
tx: "off"

## Adaptive RX/TX
adaptive_rx: "off"
adaptive_tx: "off"

## RX/TX polling interval
rx_usecs: 0
tx_usecs: 0

## RX/TX polling queue length
rx_frames: 1
tx_frames: 1

## NAPI
napi_defer_hard_irqs: 1
gro_flush_timeout: 1
threaded_napi: 1

## RPS & RFS
## https://docs.kernel.org/networking/scaling.html
## https://www.suse.com/de-de/support/kb/doc/?id=000018430
## https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/performance_tuning_guide/network-rps#network-rps
rps: false
