---
- name: Install packages
  import_tasks: packages.yml
  tags: packages

- name: Configure logging
  import_tasks: logging.yml
  tags: logging

- name: Configure limits
  import_tasks: limits.yml
  tags: limits

- name: Configure network interfaces
  import_tasks: nic.yml
  tags: nic

- name: Disable the netfilter
  import_tasks: netfilter.yml
  tags: disable-netfilter
  when: firewall == 'none'

- name: Configure nftables
  import_tasks: nftables.yml
  tags: nftables
  when: firewall == 'nftables'

- name: Configure iptables
  import_tasks: iptables.yml
  tags: iptables
  when: firewall == 'iptables'

- name: Disable and stop unnecessary services
  import_tasks: services.yml
  tags: services

- name: Apply sysctl settings
  import_tasks: sysctl.yml
  tags: sysctl

- name: Configure Kernel
  import_tasks: kernel.yml
  tags: kernel
