---
- name: Disable nftables service
  systemd:
    name: nftables
    enabled: false
    state: stopped
  ignore_errors: true

- name: Disable iptables service
  systemd:
    name: iptables
    enabled: false
    state: stopped
  ignore_errors: true

- name: Blacklist netfilter modules
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disable-netfilter.conf
    content: |
      blacklist nft_compat
      blacklist nfnetlink
      blacklist ipt_REJECT
      blacklist x_tables
      blacklist ip_tables
      blacklist iptable_filter
      blacklist iptable_nat
      blacklist iptable_mangle
      blacklist iptable_raw
      blacklist ip6_tables
      blacklist ip6table_filter
      blacklist ip6table_nat
      blacklist ip6table_mangle
      blacklist ip6table_raw
      blacklist nf_tables
      blacklist nf_tables_set
      blacklist nf_conntrack
      blacklist nf_conntrack_netlink
      blacklist nf_conntrack_ipv4
      blacklist nf_conntrack_ipv6
      blacklist nf_conntrack_ftp
      blacklist nf_conntrack_sip
      blacklist nf_conntrack_tftp
      blacklist nf_nat
      blacklist nf_nat_ipv4
      blacklist nf_nat_ipv6
      blacklist nf_nat_ftp
      blacklist nf_nat_sip
      blacklist nf_nat_tftp
      blacklist nf_reject_ipv4
      blacklist nf_reject_ipv6
      blacklist nf_defrag_ipv4
      blacklist nf_defrag_ipv6
      blacklist nf_log_ipv4
      blacklist nf_log_ipv6
      blacklist nf_log_arp
      blacklist xt_conntrack
      blacklist xt_MASQUERADE
      blacklist xt_mark
      blacklist xt_owner
      blacklist xt_recent
      blacklist xt_limit
      blacklist xt_nat
      blacklist xt_tcpudp
      blacklist xt_state
      blacklist xt_LOG
      blacklist xt_CT
      blacklist xt_multiport
      blacklist xt_comment
      blacklist br_netfilter
